# Generated by Django 2.1.8 on 2019-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starid', models.CharField(max_length=100, verbose_name='ID Звезды')),
                ('name', models.CharField(max_length=100, verbose_name='Владелец')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('magnitude', models.CharField(max_length=100, verbose_name='Звездная величина')),
                ('constellation', models.CharField(max_length=100, verbose_name='Созвездие')),
                ('date', models.DateField()),
            ],
        ),
    ]
