# Generated by Django 2.1.8 on 2019-07-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Catalogue',
        ),
    ]
