# Generated by Django 2.1.8 on 2019-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20190717_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiimage',
            old_name='img',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/promotions/', verbose_name='Image'),
        ),
    ]
