# Generated by Django 2.1.8 on 2019-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20190815_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='magnitude',
            field=models.FloatField(verbose_name='Звездная величина'),
        ),
    ]
