# Generated by Django 2.1.8 on 2019-08-15 22:26

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=oscar.models.fields.NullCharField(max_length=64, verbose_name='UPC'),
        ),
    ]
