# Generated by Django 2.1.8 on 2019-09-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_flatpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='image',
        ),
    ]
