# Generated by Django 2.1.8 on 2019-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_remove_flatpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
