# Generated by Django 2.1.8 on 2019-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_flatpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='image',
        ),
        migrations.AddField(
            model_name='flatpage',
            name='abs_magnitude',
            field=models.CharField(max_length=2, null=True, verbose_name='absolute magnitude'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='constellation',
            field=models.CharField(max_length=100, null=True, verbose_name='constellation'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='constellation_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='constellation image'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='diameter',
            field=models.CharField(max_length=20, null=True, verbose_name='diameter'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='distance',
            field=models.CharField(max_length=20, null=True, verbose_name='distance'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='draper',
            field=models.CharField(max_length=20, null=True, verbose_name='draper'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='luminocity',
            field=models.CharField(max_length=20, null=True, verbose_name='luminocity'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='magnitude',
            field=models.CharField(max_length=20, null=True, verbose_name='visual magnitude'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='spectrum',
            field=models.CharField(max_length=20, null=True, verbose_name='spectrum'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='starclass',
            field=models.CharField(max_length=100, null=True, verbose_name='starclass'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='starclass_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='starclass image'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='telescope1',
            field=models.ImageField(null=True, upload_to='', verbose_name='telescope 1'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='telescope1_label',
            field=models.CharField(max_length=20, null=True, verbose_name='telescope 1 label'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='telescope2',
            field=models.ImageField(null=True, upload_to='', verbose_name='telescope 2'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='telescope2_label',
            field=models.CharField(max_length=20, null=True, verbose_name='telescope 2 label'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='temperature',
            field=models.CharField(max_length=20, null=True, verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='enable_comments',
            field=models.BooleanField(default=False, null=True, verbose_name='enable comments'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
