# Generated by Django 2.1.8 on 2019-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0006_auto_20190930_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='constellation_img',
            field=models.CharField(max_length=200, null=True, verbose_name='constellation image'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='starclass_img',
            field=models.CharField(max_length=200, null=True, verbose_name='starclass image'),
        ),
    ]
