# Generated by Django 2.1.8 on 2019-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_auto_20190930_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpage',
            old_name='telescope1_label',
            new_name='telescope1label',
        ),
        migrations.RenameField(
            model_name='flatpage',
            old_name='telescope2_label',
            new_name='telescope2label',
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='abs_magnitude',
            field=models.CharField(max_length=20, null=True, verbose_name='absolute magnitude'),
        ),
    ]
