# Generated by Django 2.1.8 on 2019-10-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0008_auto_20191001_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpage',
            old_name='telescope1label',
            new_name='telescope1_label',
        ),
        migrations.RenameField(
            model_name='flatpage',
            old_name='telescope2label',
            new_name='telescope2_label',
        ),
    ]
