# Generated by Django 2.1.8 on 2019-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0009_auto_20191001_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='owner',
            field=models.CharField(max_length=100, null=True, verbose_name='owner'),
        ),
    ]
