# Generated by Django 2.1.8 on 2019-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0011_flatpage_coordinates_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='ascension',
            field=models.CharField(max_length=40, null=True, verbose_name='ascension'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='declination',
            field=models.CharField(max_length=40, null=True, verbose_name='declinatio'),
        ),
    ]
