# Generated by Django 2.1.8 on 2019-10-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0012_auto_20191001_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpage',
            old_name='ascension',
            new_name='right_ascension',
        ),
    ]
