# Generated by Django 2.1.8 on 2019-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0013_auto_20191001_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='coordinates_fullscreen',
        ),
        migrations.AddField(
            model_name='flatpage',
            name='coordinates_1to1',
            field=models.ImageField(null=True, upload_to='', verbose_name='coordinates 1 to 1'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='coordinates_1to4',
            field=models.ImageField(null=True, upload_to='', verbose_name='coordinates 1 to 4'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='coordinates_1to8',
            field=models.ImageField(null=True, upload_to='', verbose_name='coordinates 1 to 8'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='declination',
            field=models.CharField(max_length=40, null=True, verbose_name='declination'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='right_ascension',
            field=models.CharField(max_length=40, null=True, verbose_name='right ascension'),
        ),
    ]
