# Generated by Django 2.1.8 on 2019-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0014_auto_20191001_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='coordinates_fullscreen',
            field=models.ImageField(null=True, upload_to='', verbose_name='coordinates fullscreen'),
        ),
    ]
