# Generated by Django 2.1.8 on 2019-10-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0015_flatpage_coordinates_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='video',
            field=models.URLField(blank=True, verbose_name='video'),
        ),
    ]
