# Generated by Django 2.1.8 on 2019-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0016_flatpage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='dossier_1_cn',
            field=models.TextField(null=True, verbose_name='dossier_1_content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='dossier_1_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='dossier 1 image'),
        ),
    ]
