# Generated by Django 2.1.8 on 2019-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0017_auto_20191002_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='dossier_2_cn',
            field=models.TextField(null=True, verbose_name='dossier 2 content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='dossier_2_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='dossier 2 image'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='dossier_1_cn',
            field=models.TextField(null=True, verbose_name='dossier 1 content'),
        ),
    ]
