# Generated by Django 2.1.8 on 2019-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0018_auto_20191003_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='dossier_3_cn',
            field=models.TextField(blank=True, null=True, verbose_name='dossier 3 content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='dossier_3_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='dossier 3 image'),
        ),
    ]
