# Generated by Django 2.1.8 on 2019-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0019_auto_20191003_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='dossier_4_cn',
            field=models.TextField(blank=True, null=True, verbose_name='dossier 4 content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='dossier_4_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='dossier 4 image'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='dossier_3_cn',
            field=models.TextField(null=True, verbose_name='dossier 3 content'),
        ),
    ]
