# Generated by Django 2.1.8 on 2019-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0021_auto_20191004_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='dossier_6_cn',
            field=models.TextField(blank=True, null=True, verbose_name='dossier 5 content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='dossier_6_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='dossier 5 image'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='dossier_5_cn',
            field=models.TextField(null=True, verbose_name='dossier 5 content'),
        ),
    ]
