# Generated by Django 2.1.8 on 2019-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0024_auto_20191004_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='content',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
