# Generated by Django 2.1.15 on 2021-01-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='partner_sku',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Складская запись'),
        ),
    ]
