# Generated by Django 2.1.15 on 2021-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20210123_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='partner_sku',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Складская запись'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
    ]
